-- Titan Gym prototype schema. The anon policies below expose member data publicly.
create table if not exists public.members (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  plan text not null,
  price numeric(12, 2) not null check (price >= 0),
  goal text,
  start_date date not null,
  end_date date not null,
  created_at timestamptz not null default now()
);

alter table public.members enable row level security;

grant usage on schema public to anon;
grant select, insert, update, delete on public.members to anon;
grant usage, select on sequence public.members_id_seq to anon;

drop policy if exists "Public can register members" on public.members;
create policy "Public can register members"
  on public.members for insert to anon
  with check (true);

drop policy if exists "Prototype dashboard can read members" on public.members;
create policy "Prototype dashboard can read members"
  on public.members for select to anon
  using (true);

drop policy if exists "Prototype dashboard can update members" on public.members;
create policy "Prototype dashboard can update members"
  on public.members for update to anon
  using (true)
  with check (true);

drop policy if exists "Prototype dashboard can delete members" on public.members;
create policy "Prototype dashboard can delete members"
  on public.members for delete to anon
  using (true);

create index if not exists members_created_at_idx
  on public.members (created_at desc);

-- Enable dashboard live updates when Supabase Realtime is available in this project.
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
     and not exists (
       select 1
       from pg_publication_tables
       where pubname = 'supabase_realtime'
         and schemaname = 'public'
         and tablename = 'members'
     ) then
    execute 'alter publication supabase_realtime add table public.members';
  end if;
end
$$;